In [24]:
from graphviz import Digraph
from IPython.display import Image
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import export_graphviz
import graphviz
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the Iris dataset


In [25]:
df = pd.read_csv('iris.csv')

# Display unique species count (this can help verify the target variable)


In [26]:
# print(f"Number of unique species: {df['Species'].nunique()}")

# Define the features and target variable


In [27]:
X = df.drop('Species', axis=1)
y = df['Species']

# Split the data into training and testing sets (60% train, 40% test to reduce accuracy)


In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Initialize and train the Decision Tree Classifier with limited depth


In [29]:
dt_classifier = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

# Make predictions on the test set


In [30]:
y_pred = dt_classifier.predict(X_test)

# Calculate accuracy and confusion matrix


In [31]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Display the results


In [32]:
print("Accuracy:", round(accuracy * 100, 2), "%")
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 98.33 %
Confusion Matrix:
 [[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]
